"""
Generator Agent - Cover Letter Document Generation.

This module contains the GeneratorAgent class, which generates personalized
cover letter documents in Word (.docx) format. The agent uses an LLM to write
cover letter content based on candidate profiles, job analyses, and selected
writing styles.

The generated documents include:
- Contact information placeholders
- Date and recipient placeholders
- LLM-generated cover letter body
- Signature section
"""

import os
import logging
from datetime import datetime

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

from jobsai.config.paths import COVER_LETTER_PATH
from jobsai.config.prompts import (
    GENERATOR_SYSTEM_PROMPT as SYSTEM_PROMPT,
    GENERATOR_USER_PROMPT as USER_PROMPT,
)

from jobsai.utils.llms import call_llm
from jobsai.utils.normalization import normalize_text

logger = logging.getLogger(__name__)


class GeneratorAgent:
    """Agent responsible for generating personalized cover letter documents.

    Creates Word documents (.docx) with professionally formatted cover letters
    tailored to specific job positions. Uses an LLM to generate the cover letter
    content based on candidate profiles, job analyses, and selected writing styles.

    The documents are formatted as standard business letters with placeholders
    for contact information, recipient details, and signature that users can
    fill in manually before sending.

    Args:
        timestamp (str): Backend-wide timestamp for consistent file naming.
            Format: YYYYMMDD_HHMMSS (e.g., "20250115_143022")
    """

    def __init__(self, timestamp: str):
        self.timestamp = timestamp

    # ------------------------------
    # Public interface
    # ------------------------------
    def generate_letters(self, job_analysis: str, profile: str, style: str) -> Document:
        """Generate a personalized cover letter document for job applications.

        Creates a Word document with a professionally formatted cover letter
        tailored to the specific job position. The cover letter content is
        generated by an LLM based on the candidate profile, job analysis, and
        selected writing style.

        Args:
            job_analysis (str): Job analysis containing cover letter writing
                instructions generated by AnalyzerAgent. Includes job details
                and personalized guidance for highlighting relevant skills.
            profile (str): Candidate profile text describing skills, experience,
                and professional characteristics.
            style (str): Writing style/tone for the cover letter. Options:
                - "Professional": Clear, respectful, concise tone
                - "friendly": Warm, positive but professional tone
                - "confident": Confident, proactive tone without arrogance
                Defaults to "Professional" if style not recognized.

        Returns:
            Document: python-docx Document object containing the formatted
                cover letter. The document is also saved to disk at:
                {COVER_LETTER_PATH}/{timestamp}_cover_letter.docx
        """

        # Build the system prompt
        # Map style names to tone instructions for the LLM
        tone_instructions = {
            "Professional": "Write in a clear, respectful, concise, professional tone. Use well-structured paragraphs. Avoid exaggerations.",
            "friendly": "Write in a warm, positive tone but keep it professional.",
            "confident": "Write with a confident, proactive tone without sounding arrogant.",
        }
        base_style = tone_instructions.get(style, tone_instructions["Professional"])
        system_prompt = SYSTEM_PROMPT.format(base_style=base_style)

        # Build the user prompt
        # Format user prompt with candidate profile and job analysis
        user_prompt = USER_PROMPT.format(profile=profile, job_analysis=job_analysis)

        # Generate and format the cover letter documents
        cover_letters = self._write_letters(system_prompt, user_prompt)

        return cover_letters

    # ------------------------------
    # Internal function
    # ------------------------------
    def _write_letters(self, system_prompt: str, user_prompt: str) -> Document:
        """Create and format the cover letter Word document.

        Builds a professionally formatted business letter document with:
        1. Contact information placeholders (top-right)
        2. Current date (top-right)
        3. Recipient placeholders (top-right)
        4. LLM-generated cover letter body (main content)
        5. Signature placeholders (bottom-right)

        The document follows standard business letter formatting conventions.
        All placeholders (contact info, recipient, signature) should be filled
        in manually by the user before sending.

        Args:
            system_prompt (str): System prompt defining the LLM's role and
                writing style instructions for cover letter generation.
            user_prompt (str): User prompt containing candidate profile and
                job analysis with specific instructions for the cover letter.

        Returns:
            Document: python-docx Document object containing the complete
                formatted cover letter. The document is automatically saved
                to disk at {COVER_LETTER_PATH}/{timestamp}_cover_letter.docx
        """
        cover_letter = Document()

        # Add contact information section (top-right aligned)
        # Format: website, LinkedIn, GitHub (blank line) email, phone
        # Users should replace placeholders with their actual information
        contact_paragraph = cover_letter.add_paragraph()
        contact_paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        contact_paragraph.add_run("ADD WEBSITE\n")
        contact_paragraph.add_run("ADD LINKEDIN\n")
        contact_paragraph.add_run("ADD GITHUB\n\n")
        contact_paragraph.add_run("ADD EMAIL\n")
        contact_paragraph.add_run("ADD PHONE\n\n")

        # Convert timestamp to human-readable date format
        # Input format: YYYYMMDD_HHMMSS (e.g., "20250115_143022")
        # Output format: "Month Day, Year" (e.g., "January 15, 2025")
        parsed_timestamp = datetime.strptime(self.timestamp, "%Y%m%d_%H%M%S")
        pretty_date = parsed_timestamp.strftime("%B %d, %Y")
        cover_letter.add_paragraph(f"{pretty_date}\n").alignment = (
            WD_ALIGN_PARAGRAPH.RIGHT
        )

        # Add recipient information placeholders (top-right aligned)
        # Users should fill in the actual recruiter/hiring team and company name
        cover_letter.add_paragraph("ADD RECRUITER/HIRING TEAM").alignment = (
            WD_ALIGN_PARAGRAPH.RIGHT
        )
        cover_letter.add_paragraph("ADD HIRING COMPANY/GROUP\n\n").alignment = (
            WD_ALIGN_PARAGRAPH.RIGHT
        )

        # Generate cover letter body content using LLM
        # The LLM writes personalized content based on profile and job analysis
        raw = call_llm(system_prompt, user_prompt, max_tokens=1500)
        # Normalize text: clean whitespace, line breaks, and formatting
        normalized = normalize_text(raw)
        # Insert the generated body into the document
        cover_letter.add_paragraph(normalized)

        # Add signature section (bottom-right aligned)
        cover_letter.add_paragraph("Best regards,").alignment = WD_ALIGN_PARAGRAPH.RIGHT
        cover_letter.add_paragraph("ADD YOUR NAME").alignment = WD_ALIGN_PARAGRAPH.RIGHT

        # Save document to disk for persistence and debugging
        filename = f"{self.timestamp}_cover_letter.docx"
        filepath = os.path.join(COVER_LETTER_PATH, filename)
        cover_letter.save(filepath)
        logger.info(f"Saved cover letter to {filepath}")

        return cover_letter
